xhg_plateform:
    resource: "@XHGPlateformBundle/Resources/config/routing.yml"
    prefix:   /plateform

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    
root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /plateform
        permanent: true