<?php

namespace XHG\PlateformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{

    public function getAdvertWithCategories(array $categories)
    {
        $qb = $this->createQueryBuilder('a')
                ->innerJoin('a.categories', 'cat')
                ->addSelect('cat')
                ->where($qb->expr()->in('cat.name', $categories));

        return $qb->getQuery()->getResult();
    }

    public function getLastAdvert($max = 1)
    {
        $qb = $this->createQueryBuilder('a')
                ->orderBy('a.date','DESC')
                ->setMaxResults($max);
        
        return $qb->getQuery()->getResult();
    }

}
