<?php

namespace XHG\PlateformBundle\Repository;

/**
 * ApplicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationRepository extends \Doctrine\ORM\EntityRepository
{

    public function getApplicationWithAdvert($limit)
    {
        $qb = $this->createQueryBuilder('app')
                ->innerJoin('app.advert', 'adv')
                ->addSelect('adv')
                ->orderBy('app.id DESC')
                ->setMaxResults($limit);

        return $qb->getQuery()->getResult();
    }

}
