services:
    xhg_core.csv_to_array:
        class: XHG\CoreBundle\Services\ConvertCsvToArray
    
    xhg_core.mailer:
        class: XHG\CoreBundle\Services\Mailer
        arguments:
            - "@mailer"
