services:
    xhg_plateform.antispam:
        class: XHG\PlateformBundle\Antispam\XHGAntispam
        arguments:
            - "@mailer"
            - "%locale%"
            - 50
    xhg_plateform.doctrine_listener.entity_creation:
        class: XHG\PlateformBundle\DoctrineListener\EntityCreationListener
        arguments:
            - "@xhg_core.mailer"
        tags:
            - { name: doctrine.event_listener, event: postPersist }